import React, { useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import 'bootstrap/dist/css/bootstrap.min.css';
import './styles.css';

function FileCard({ title, subtitle, file, onPick, onRemove }) {
  const input = useRef();
  return <section className="rounded-3xl border border-slate-200 bg-white p-4 shadow-sm sm:p-6"><div className="mb-4 flex items-start justify-between gap-3"><div><h2 className="text-lg font-semibold text-slate-900">{title}</h2><p className="mb-0 text-sm text-slate-500">{subtitle}</p></div><span className="rounded-full bg-indigo-50 px-3 py-1 text-xs font-semibold text-indigo-700">Required</span></div><input ref={input} className="hidden" type="file" accept=".pdf,.docx,.txt" onChange={e => onPick(e.target.files?.[0])} />{file ? <div className="flex items-center justify-between rounded-2xl border border-emerald-200 bg-emerald-50 p-4"><div className="min-w-0"><p className="mb-0 truncate font-medium text-emerald-950">{file.name}</p><p className="mb-0 text-sm text-emerald-700">{Math.ceil(file.size / 1024)} KB ready</p></div><button className="btn btn-sm btn-outline-danger ms-3" onClick={onRemove}>Remove</button></div> : <button onClick={() => input.current.click()} className="dot-grid w-full rounded-2xl border-2 border-dashed border-slate-300 px-5 py-8 text-center transition hover:border-indigo-400 hover:bg-indigo-50"><span className="mb-2 block text-2xl">↑</span><span className="block font-semibold text-slate-800">Choose a file</span><span className="block text-sm text-slate-500">PDF, DOCX, or TXT</span></button>}</section>;
}

function App() {
  const [resume, setResume] = useState(null), [job, setJob] = useState(null), [result, setResult] = useState(null), [error, setError] = useState(''), [loading, setLoading] = useState(false);
  const analyze = async () => { if (!resume || !job) return setError('Upload both files to continue.'); setLoading(true); setError(''); setResult(null); try { const form = new FormData(); form.append('job', job); form.append('resume', resume); const response = await fetch('/api/analyze', { method: 'POST', body: form }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setResult(data); } catch (e) { setError(e.message || 'Could not analyze your files.'); } finally { setLoading(false); } };
  return <main className="min-vh-100 px-3 py-4 sm:px-6 sm:py-8"><div className="mx-auto max-w-[900px]"><nav className="mb-5 flex items-center justify-between"><a className="text-decoration-none text-xl font-bold tracking-tight text-slate-900" href="#">match<span className="text-indigo-600">wise</span></a><span className="text-sm text-slate-500">Your private career workspace</span></nav><div className="rounded-3xl bg-slate-950 px-6 py-10 text-white shadow-lg sm:px-10"><p className="mb-3 text-sm font-semibold uppercase tracking-widest text-indigo-300">Resume tailor</p><h1 className="mb-3 text-3xl font-bold tracking-tight sm:text-5xl">Put your experience<br />in the best light.</h1><p className="mb-0 max-w-xl text-slate-300">Upload a job description and your resume. We’ll identify your fit and prepare you for the interview.</p></div><div className="mt-5 grid gap-4 md:grid-cols-2"><FileCard title="Job description" subtitle="The role you’re applying for" file={job} onPick={setJob} onRemove={() => setJob(null)} /><FileCard title="Your resume" subtitle="Your current CV or résumé" file={resume} onPick={setResume} onRemove={() => setResume(null)} /></div><div className="mt-5 rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:flex sm:items-center sm:justify-between sm:p-6"><div><h2 className="mb-1 text-lg font-semibold text-slate-900">Ready when you are</h2><p className="mb-0 text-sm text-slate-500">Files are used only for this request and not stored by the app.</p></div><button className="btn btn-primary mt-4 px-4 py-2 font-semibold sm:mt-0" disabled={loading} onClick={analyze}>{loading ? 'Analyzing…' : 'Analyze my match →'}</button></div>{error && <p role="alert" className="mt-3 text-center text-sm font-medium text-rose-700">{error}</p>}{result && <section className="mt-5 rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><div className="mb-5 flex items-center gap-4"><span className="grid h-16 w-16 place-items-center rounded-full bg-indigo-100 text-xl font-bold text-indigo-700">{result.matchScore}%</span><div><h2 className="mb-1 text-xl font-bold text-slate-900">Match overview</h2><p className="mb-0 text-slate-600">{result.summary}</p></div></div><div className="grid gap-5 md:grid-cols-2"><div><h3 className="text-base font-bold text-slate-900">Your strengths</h3><ul className="ps-4 text-slate-600">{result.strengths?.map((x, i) => <li key={i}>{x}</li>)}</ul></div><div><h3 className="text-base font-bold text-slate-900">Gaps to address</h3><ul className="ps-4 text-slate-600">{result.gaps?.map((x, i) => <li key={i}>{x}</li>)}</ul></div></div><h3 className="mt-5 text-lg font-bold text-slate-900">Interview practice</h3><div className="space-y-3">{result.questions?.map((x, i) => <article key={i} className="rounded-2xl bg-slate-50 p-4"><p className="mb-2 font-semibold text-slate-900">{x.question}</p><p className="mb-0 text-slate-600">{x.answer}</p></article>)}</div></section>}</div></main>;
}
createRoot(document.getElementById('root')).render(<App />);
